# 00. PyTorch Fundamentals Exercises - Version 2

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).


In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(5, 5)`.

In [1]:
# Import torch
import torch

# Create random tensor
tensor55=torch.rand(5,5)
print(tensor55)

tensor([[0.9378, 0.0175, 0.1359, 0.5989, 0.1191],
        [0.5522, 0.0551, 0.7959, 0.8416, 0.4378],
        [0.8588, 0.0604, 0.6088, 0.8716, 0.5998],
        [0.7951, 0.7691, 0.4894, 0.7175, 0.3127],
        [0.4052, 0.6214, 0.9939, 0.2427, 0.2076]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 5)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor15 = torch.rand(1,5)

# Perform matrix multiplication
tensor51=tensor15.T
matmulRes = torch.matmul(tensor55, tensor51)
print (matmulRes)
print (matmulRes.shape)


tensor([[0.6758],
        [1.4220],
        [1.4285],
        [1.7668],
        [1.4869]])
torch.Size([5, 1])


### 4. Set the random seed to `42` and do 2 & 3 over again.

The resulting tensor should have shape `torch.Size([5, 1])`. Use `torch.manual_seed(42)` before creating both tensors so the results are reproducible.

In [12]:
# Set manual seed

torch.manual_seed(42)
# Create two random tensors
tensor55=torch.rand(5,5)
tensorB=torch.rand(1,5)
matmulRes = torch.matmul(tensor55, tensorB.T)
print (matmulRes)
print (matmulRes.shape)

# Matrix multiply tensors


tensor([[1.1697],
        [0.9278],
        [0.9534],
        [0.6976],
        [0.7460]])
torch.Size([5, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `2024`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(2024)

### 6. Create two random tensors of shape `(3, 4)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(99)` when creating the tensors (this doesn't have to be the GPU random seed).

The expected output structure should be something like:

```
Device: cuda
(tensor([[..., ..., ..., ...],
         [..., ..., ..., ...],
         [..., ..., ..., ...]], device='cuda:0'),
 tensor([[..., ..., ..., ...],
         [..., ..., ..., ...],
         [..., ..., ..., ...]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(99)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_A = torch.rand(3,4).to(device)
tensor_B = torch.rand(3,4).to(device)
print(f"Device: {device}")
print(tensor_A)
print(tensor_B)

# Create two random tensors on GPU


Device: cuda
tensor([[0.1033, 0.9702, 0.9481, 0.9787],
        [0.3268, 0.9200, 0.0503, 0.4583],
        [0.8608, 0.4882, 0.7981, 0.2011]], device='cuda:0')
tensor([[0.1914, 0.8979, 0.9541, 0.5242],
        [0.6006, 0.9888, 0.7474, 0.5498],
        [0.0670, 0.1168, 0.1724, 0.9940]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The resulting tensor should have shape `torch.Size([3, 3])`.

In [18]:
# Perform matmul on tensor_A and tensor_B
output = tensor_A @ tensor_B.T
print(output)
print(output.shape)

tensor([[2.3085, 2.2680, 1.2565],
        [1.1769, 1.3955, 0.5936],
        [1.4699, 1.7067, 0.4522]], device='cuda:0')
torch.Size([3, 3])


### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
print(output.max())


# Find min
print(output.min())

tensor(2.3085, device='cuda:0')
tensor(0.4522, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
print (output.argmax())

# Find arg min
print (output.argmin())

tensor(0, device='cuda:0')
tensor(8, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 8)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(8)`. Set the seed to `21` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output structure should look like:

```
tensor([[[[..., ..., ..., ..., ..., ..., ..., ...]]]]) torch.Size([1, 1, 1, 8])
tensor([..., ..., ..., ..., ..., ..., ..., ...]) torch.Size([8])
```

In [27]:
# Set seed
torch.manual_seed(21)

# Create random tensor
tensor=torch.rand(1,1,1,8)


# Remove single dimensions
tensor_squeezed=tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.4736, 0.6136, 0.0121, 0.0396, 0.5674, 0.2538, 0.5338, 0.6093]]]]) torch.Size([1, 1, 1, 8])
tensor([0.4736, 0.6136, 0.0121, 0.0396, 0.5674, 0.2538, 0.5338, 0.6093]) torch.Size([8])
