# Ch 00: PyTorch Fundamentals - Tensors - Exercise

**Source:** [learnpytorch.io](https://www.learnpytorch.io/)

**Goal:** Type each code cell line by line from memory to build muscle memory.

**Topics:** Tensor creation (torch.tensor, zeros, ones, rand, arange). Dtypes, shapes, devices. Basic operations: add, mul, matmul. Reshaping: view, reshape, permute, squeeze, unsqueeze.

In [ ]:
import torch
print(f"PyTorch version: {torch.__version__}")

## Start here

Add your code cells below.

In [2]:
import torch
torch.__version__

'2.12.0+cpu'

Creating tensors:

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim


0

ndim = number of dimensions = how many indices you need to reach a single value.

Scalar tensor(7) -- you already have the value. No indexing needed. ndim = 0
Vector tensor([1, 2, 3]) -- you need one index: t[0]. ndim = 1
Matrix tensor([[1,2],[3,4]]) -- you need two indices: t[0][1]. ndim = 2
Your image [3, 224, 224] -- three indices: t[0][100][50]. ndim = 3

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

Tensor's dimension: A tensor's dimension (ndim) = how many indices you need to reach a single number.


tensor(7)                     # 0 indices needed → ndim = 0 (scalar)

tensor([1, 2, 3])             # t[0] → ndim = 1 (vector)

tensor([[1, 2],               # t[0][1] → ndim = 2 (matrix)
        [3, 4]])

tensor([[[1, 2], [3, 4]],     # t[0][1][0] → ndim = 3
        [[5, 6], [7, 8]]])
Count the opening brackets on the left side -- that's your ndim. One [ = 1D, [[ = 2D, [[[ = 3D.

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
vector2 = torch.tensor([7, 7,7,7])
vector2

tensor([7, 7, 7, 7])

In [10]:
vector2.shape

torch.Size([4])

In [15]:
MATRIX2 = torch.tensor([[7, 8,5], 
                       [9, 10,11]])
MATRIX2

tensor([[ 7,  8,  5],
        [ 9, 10, 11]])

In [16]:
MATRIX2.shape


torch.Size([2, 3])

In [17]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim


3

TENSOR = torch.tensor([[[1, 2, 3],    # 3 numbers per row
                        [3, 6, 9],    # 3 rows
                        [2, 4, 5]]])  # 1 such block
3 -- each row has 3 elements
3 -- there are 3 rows in the grid
1 -- there is 1 grid
So torch.Size([1, 3, 3]) = 1 plane of 3 rows of 3 columns.

Count the opening brackets to confirm: [[[ = 3 levels deep = 3 numbers in the shape.

In [19]:
TENSOR.shape


torch.Size([1, 3, 3])

Random tensors
In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

In [20]:
random_tensor = torch.rand(size=(3,4))

In [23]:
random_tensor, random_tensor.dtype

(tensor([[0.0536, 0.8864, 0.6014, 0.9834],
         [0.2700, 0.2407, 0.2256, 0.9873],
         [0.4364, 0.5069, 0.9661, 0.0506]]),
 torch.float32)

In [24]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))


In [25]:
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [27]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)


In [28]:
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\Lucie\AppData\Local\Temp\ipykernel_30356\1975812094.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes¶
https://docs.pytorch.org/docs/2.12/tensors.html#data-types

Getting information from tensors¶
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7315, 0.2927, 0.4271, 0.8870],
        [0.2612, 0.0060, 0.9557, 0.9552],
        [0.2255, 0.9472, 0.7355, 0.5760]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


============ DONE 5-19-2026 ==============

============== START 5-20-2026 ============